package com.kvarela;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String address;
   private java.lang.Boolean hoaApproval;
   private java.util.Date hoaMeetingDate;
   private java.lang.String salesman;

   public Order()
   {
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.Boolean getHoaApproval()
   {
      return this.hoaApproval;
   }

   public void setHoaApproval(java.lang.Boolean hoaApproval)
   {
      this.hoaApproval = hoaApproval;
   }

   public java.util.Date getHoaMeetingDate()
   {
      return this.hoaMeetingDate;
   }

   public void setHoaMeetingDate(java.util.Date hoaMeetingDate)
   {
      this.hoaMeetingDate = hoaMeetingDate;
   }

   public java.lang.String getSalesman()
   {
      return this.salesman;
   }

   public void setSalesman(java.lang.String salesman)
   {
      this.salesman = salesman;
   }

   public Order(java.lang.String address, java.lang.Boolean hoaApproval,
         java.util.Date hoaMeetingDate, java.lang.String salesman)
   {
      this.address = address;
      this.hoaApproval = hoaApproval;
      this.hoaMeetingDate = hoaMeetingDate;
      this.salesman = salesman;
   }

}