package com.kvarela;

/**
 * This class was automatically generated by the data modeler tool.
 */

public enum Status implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Status() {
    }

}