package com.kvarela;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class teste implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TESTE_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "TESTE_ID_GENERATOR", sequenceName = "TESTE_ID_SEQ")
    private java.lang.Long id;

    public teste() {
    }
    
    public teste(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}