package com.redhat.example.sv_model.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ElectricalPermit implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String owner;
   private java.util.Date submitDate;
   private boolean approved;
   private java.lang.Double totalCost;

   private java.lang.String address;

   public ElectricalPermit()
   {
   }

   public java.lang.String getOwner()
   {
      return this.owner;
   }

   public void setOwner(java.lang.String owner)
   {
      this.owner = owner;
   }

   public java.util.Date getSubmitDate()
   {
      return this.submitDate;
   }

   public void setSubmitDate(java.util.Date submitDate)
   {
      this.submitDate = submitDate;
   }

   public boolean isApproved()
   {
      return this.approved;
   }

   public void setApproved(boolean approved)
   {
      this.approved = approved;
   }

   public java.lang.Double getTotalCost()
   {
      return this.totalCost;
   }

   public void setTotalCost(java.lang.Double totalCost)
   {
      this.totalCost = totalCost;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public ElectricalPermit(java.lang.String owner, java.util.Date submitDate,
         boolean approved, java.lang.Double totalCost, java.lang.String address)
   {
      this.owner = owner;
      this.submitDate = submitDate;
      this.approved = approved;
      this.totalCost = totalCost;
      this.address = address;
   }

}