package com.redhat.example.sv_model.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable
{

   private java.util.Date hoaMeetingDate;

   private boolean hoaApproval;

   private java.lang.String address;

   private java.lang.String salesman;

   private java.lang.String status;

   public NewOrder()
   {
   }

   public java.util.Date getHoaMeetingDate()
   {
      return this.hoaMeetingDate;
   }

   public void setHoaMeetingDate(java.util.Date hoaMeetingDate)
   {
      this.hoaMeetingDate = hoaMeetingDate;
   }

   public boolean isHoaApproval()
   {
      return this.hoaApproval;
   }

   public void setHoaApproval(boolean hoaApproval)
   {
      this.hoaApproval = hoaApproval;
   }

   public String toString()
   {
      return "New Order Date: " + this.isHoaApprovalHoaMeetingDate() + ", Hoa approval:" + this.isHoaApproval();

   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.String getSalesman()
   {
      return this.salesman;
   }

   public void setSalesman(java.lang.String salesman)
   {
      this.salesman = salesman;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public NewOrder(java.util.Date hoaMeetingDate, boolean hoaApproval,
         java.lang.String address, java.lang.String salesman,
         java.lang.String status)
   {
      this.hoaMeetingDate = hoaMeetingDate;
      this.hoaApproval = hoaApproval;
      this.address = address;
      this.salesman = salesman;
      this.status = status;
   }
}
