package com.redhat.example.sv_model.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.remote.Remotable
public class StructuralPermit implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String owner;
   private java.util.Date submitDate;
   private java.lang.Double totalCost;

   private java.lang.String address;

   private java.lang.String status;

   public StructuralPermit()
   {
   }

   public java.lang.String getOwner()
   {
      return this.owner;
   }

   public void setOwner(java.lang.String owner)
   {
      this.owner = owner;
   }

   public java.util.Date getSubmitDate()
   {
      return this.submitDate;
   }

   public void setSubmitDate(java.util.Date submitDate)
   {
      this.submitDate = submitDate;
   }

   public java.lang.Double getTotalCost()
   {
      return this.totalCost;
   }

   public void setTotalCost(java.lang.Double totalCost)
   {
      this.totalCost = totalCost;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public StructuralPermit(java.lang.String owner, java.util.Date submitDate,
         java.lang.Double totalCost, java.lang.String address,
         java.lang.String status)
   {
      this.owner = owner;
      this.submitDate = submitDate;
      this.totalCost = totalCost;
      this.address = address;
      this.status = status;
   }

}